server:
  port: ${PORT:0}

spring:
  application:
    name: user-service
  jmx:
    enabled: false
  rabbitmq:
      addresses: amqps://iejdfvfi:akgz0vZvsiZqNmobXeCxSRS_9fVKWny1@puffin.rmq2.cloudamqp.com/iejdfvfi
      queue: auth
      exchange:
        name: auth_exchange
      routing:
        key: auth_routing_key
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/db-user
    username: celodev
    password: wemocaju
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
  sql:
    init:
      mode: always
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
      
